name: at_a_glance
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.4.3
  firebase_database: ^10.0.15
  firebase_storage: ^11.0.15
  image_picker: ^0.8.7

  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5

  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_osm_plugin: any

  fluttertoast: ^8.2.1


  cupertino_icons: ^1.0.2
  asbool: ^1.0.6
  velocity_x: ^3.6.0
  flutter_dotenv: ^5.0.2
  chat_gpt_sdk: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - images/
    - .env

